import Head from "next/head";
import Chat from '../components/Main';
import RoomAndId from "../components/RoomAndUser";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RoomAndId/>
    </div>
  );
}
