import Head from "next/head";
import RoomAndId from "../components/RoomAndUser";
import io from "socket.io-client";

    const socket = io.connect("http://localhost:3001");
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RoomAndId io={socket}/>
    </div>
  );
}
